# Sample workflow for running typedoc to create documentation
name: Run typedoc to create documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
    paths:
      - src/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Run TypeDoc
        run: npm run typedoc
      - name: Push Changes
        uses: actions-go/push@master
        with:
          commit-message: '[Auto] update docs'
  
  # Deployment job
  deploy:
    if: github.ref_name == 'master'
    uses: ./.github/workflows/pages.yml 
    needs: build
  